# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20170422_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_correct',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
