# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20170422_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(default='nickname', max_length=100),
            preserve_default=False,
        ),
    ]
